name: tinger
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  args: ^2.4.1
  console_bars: ^1.1.0
  http: ^1.0.0
  udp: ^5.0.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
